<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="102595" started-at="2019-06-09T08:48:10Z" finished-at="2019-06-09T08:49:53Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="102595" started-at="2019-06-09T08:48:10Z" finished-at="2019-06-09T08:49:53Z">
      <class name="TestCases.MyStockTest">
        <test-method status="FAIL" signature="AddStockTest(java.util.Hashtable)[pri:0, instance:TestCases.MyStockTest@64485a47]" name="AddStockTest" duration-ms="101342" started-at="2019-06-09T08:48:11Z" data-provider="AddStockTestData" finished-at="2019-06-09T08:49:52Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{StockPrice=1200.0, PortfolioName=My 2019 Stocks, Comment=, Quantity=1000.0, StockName=Bosch Ltd}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Given Stock : Bosch Ltd is not present in this Portfolio expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Given Stock : Bosch Ltd is not present in this Portfolio expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at PageClasses.MyPorfolioPage.verifyStock(MyPorfolioPage.java:110)
at TestCases.MyStockTest.AddStockTest(MyStockTest.java:51)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AddStockTest -->
        <test-method status="PASS" signature="flushReports()[pri:0, instance:TestCases.MyStockTest@64485a47]" name="flushReports" is-config="true" duration-ms="549" started-at="2019-06-09T08:49:52Z" finished-at="2019-06-09T08:49:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- flushReports -->
      </class> <!-- TestCases.MyStockTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
